apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce
  labels:
    name: ecommerce
    tier: microservices
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ecommerce
data:
  NODE_ENV: "production"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "ecommerce"
  DB_USERNAME: "postgres"
  REDIS_URL: "redis://redis-service:6379"
  KAFKA_BROKERS: "kafka-service:9092"
  KAFKA_CLIENT_ID: "ecommerce-microservices"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ecommerce
type: Opaque
data:
  # Base64 encoded values
  DB_PASSWORD: cGFzc3dvcmQ=  # password
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleQ==  # your-super-secret-jwt-key
  SMTP_PASSWORD: c210cF9wYXNzd29yZA==  # smtp_password
  TWILIO_AUTH_TOKEN: dHdpbGlvX2F1dGhfdG9rZW4=  # twilio_auth_token
